### ISSUE TITLE
Updated syntax to Python 3

### ISSUE THREAD

**Issue by JasperBoom** [dewyman/TranscriptClean#17]
Hey,

I am currently trying to create a Dockerfile of the new TranscriptClean version for [BioContainers](https://github.com/BioContainers/containers).
I noticed a [update](https://github.com/dewyman/TranscriptClean/commit/fa47b0d2fa2017ffb44a790c67d1fd4e3fa1464c) to "get_SJs_from_gtf.py" for python 3, could this update also be applied to "get_corrected_SJs_from_log.py" and "clean_splice_jns.py"?
I can then finalize the container and utilize the MultiThreading in the pipeline. Thank you!

**Comment by dewyman** [comment]
Sure, I will take a look! Thanks for your work on this!

**Comment by dewyman** [comment]
Ok both of those scripts turned out to be old versions of things that aren't relevant to the current TranscriptClean, so I went ahead and removed them.
