### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by amaque** [dewyman/TranscriptClean#7]
Hi,
I'm using TranscriptClean to corrects mismatches in long reads 
> (python2.7 TranscriptClean.py --sam /genoma/cDNA_Bham_Run1.sam --genome /hg38/GRCh38.primary_assembly.genome_filter.fa --outprefix /Map/outputfile_transClean)

But I had the following error:

> Reading genome ..............................
> No splice annotation provided. Will skip splice junction correction.
> No variant file provided. Transcript correction will not be variant-aware.
> Processing SAM file .........................
> Traceback (most recent call last):
>   File "TranscriptClean.py", line 994, in <module>
>     main()
>   File "TranscriptClean.py", line 132, in main
>     canTranscripts, noncanTranscripts = processSAM(samFile, genome, sjDict, oSam, oFa, transcriptLog, primaryOnly) 
>   File "TranscriptClean.py", line 207, in processSAM
>     t = Transcript2(line, genome, spliceAnnot)
>   File "/home/joel/Documents/Soft_joe/TranscriptClean/transcript2.py", line 60, in __init__
>     self.NM, self.MD = self.getNMandMDFlags(genome)
>   File "/home/joel/Documents/Soft_joe/TranscriptClean/transcript2.py", line 344, in getNMandMDFlags
>     refBase = genome.sequence({'chr': self.CHROM, 'start': genomePos, 'stop': genomePos}, one_based=True) 
>   File "/home/joel/anaconda3/envs/py27/lib/python2.7/site-packages/pyfasta/fasta.py", line 197, in sequence
>     assert 'chr' in f and f['chr'] in self, (f, f['chr'], self.keys())
> AssertionError: ({'start': 104265275, 'chr': 'chr12', 'stop': 104265275}, 'chr12', ['chr5 5', 'chrY Y', 'chr4 4', 'chr7 7', 'chr19 19', 'chr22 22', 'chr8 8', 'chr14 14', 'chr17 17', 'chr21 21', 'chr6 6', 'chr3 3', 'chr2 2', 'chr20 20', 'chr12 12', 'chrX X', 'chr1 1', 'chr11 11', 'chr9 9', 'chr18 18', 'chr10 10', 'chr15 15', 'chrM MT', 'chr16 16', 'chr13 13'])

Do you have any suggestions to correct it?
Thanks

**Comment by dewyman** [comment]
Hi, sorry for the late response- I've been out of town. 

From this error, it looks to me like the chromosome names in your sam file do not match the chromosome names in your genome fasta file (notice how the fasta chromosomes are ['chr5 5', 'chrY Y', 'chr4 4', 'chr7 7', 'chr19 19', 'chr22 22', 'chr8 8', 'chr14 14', 'chr17 17', 'chr21 21', 'chr6 6', 'chr3 3', 'chr2 2', 'chr20 20', 'chr12 12', 'chrX X', 'chr1 1', 'chr11 11', 'chr9 9', 'chr18 18', 'chr10 10', 'chr15 15', 'chrM MT', 'chr16 16', 'chr13 13']). 

I would 1) double-check that the fasta file you're running TranscriptClean with is the same one that you used when mapping the reads to the genome, and 2) look at the lines of the fasta file that start with ">". Sometimes when these header lines contain the chromosome name plus a description with spaces in it, it creates problems when Pyfasta is reading in the names of each chromosome. A potential solution in this case is to trim these headers to just ">chr1", ">chr2", and so on.

**Comment by amaque** [comment]
Thank you! 
I was able to correct mismatches

**Comment by dewyman** [comment]
Great! Happy to help.
